<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="allegro_hand_right">
<xacro:macro name="allegro_hand_right">
    <xacro:property name="DEG2RAD" value="0.01745329251"/>
    
<!-- P.S. ALL THE REFERENCE TAXELS POSITIONS MUST BE MEASURED AND THEIR LOCATIONS SHOULD BE SPECIFIED IN THIS FILE-->

    <!-- ======================== BASE PARAMS ========================= -->
    <xacro:property name="palm_link_z" value="0.095"/>

    <!-- ======================== FINGER PARAMS ======================== -->
    <xacro:property name="links_x" value="0.0196"/>
    <xacro:property name="links_y" value="0.0275"/>
    <xacro:property name="link0_z" value="0.0164"/>
    <xacro:property name="link1_z" value="0.0540"/>
    <xacro:property name="link2_z" value="0.0384"/>

    <!-- full height from joint to tip. when used,
    the radius of the finger tip sphere will be subtracted
    and one fixed link will be added for the tip. -->
    <xacro:property name="link3_z" value="0.0387"/>
    <xacro:property name="fingerTip_r" value="0.0120"/>
    <xacro:property name="offset_origin_x_const" value="0"/>
    <xacro:property name="offset_origin_y_const" value="0.0435"/>
    <xacro:property name="offset_origin_z_const" value="-0.001542"/>
    <xacro:property name="offset_origin_z_mid_const" value="0.0007"/>

    <!-- ========================= THUMB PARAMS ========================= -->
    <xacro:property name="link0_t_x" value="0.0358"/>
    <xacro:property name="link0_t_y" value="0.0340"/>
    <xacro:property name="link0_t_z" value="0.0455"/>
    <xacro:property name="link1_t_z" value="0.0177"/>
    <xacro:property name="link2_t_z" value="0.0514"/>
    <xacro:property name="link3_t_z" value="0.0543"/>

    <!-- ========================= LIMITS ========================= -->
    <xacro:property name="joint_safety_margin" value="0.1"/>
    <xacro:property name="limit_0_up" value="0.57"/>
    <xacro:property name="limit_0_low" value="-0.57"/>
    <xacro:property name="limit_1_up" value="1.71"/>
    <xacro:property name="limit_1_low" value="-0.296"/>
    <xacro:property name="limit_2_up" value="1.809"/>
    <xacro:property name="limit_2_low" value="-0.274"/>
    <xacro:property name="limit_3_up" value="1.718"/>
    <xacro:property name="limit_3_low" value=" -0.327"/>
    <xacro:property name="limit_0_t_up" value="1.496"/>
    <xacro:property name="limit_0_t_low" value="0.363"/>
    <xacro:property name="limit_1_t_up" value="1.263"/>
    <xacro:property name="limit_1_t_low" value="-0.205"/>
    <xacro:property name="limit_2_t_up" value="1.744"/>
    <xacro:property name="limit_2_t_low" value="-0.289"/>
    <xacro:property name="limit_3_t_up" value="1.819"/>
    <xacro:property name="limit_3_t_low" value="-0.262"/>

    <!-- TAXEL MACRO-->
    <xacro:macro name="taxel" params="count ref_taxel_name sphere_radius origin_xyz origin_rpy">
            <link name="${ref_taxel_name}_${count}">
            <visual>
                    <geometry>
                        <sphere radius="${sphere_radius}"/>
                    </geometry> 
                    <material name="Orange">
                        <color rgba="${255/255} ${108/255} ${10/255} 1.0"/>
                    </material>
            </visual>

            <collision>
                <geometry>
                    <sphere radius="${sphere_radius}"/>
                </geometry>
            </collision>
        </link>

        <joint name="joint_${ref_taxel_name}_${count}" type="fixed">
            <parent link="${ref_taxel_name}_${count-1}"/>
            <child link="${ref_taxel_name}_${count}"/>
            <origin xyz="${origin_xyz}" rpy="${origin_rpy}"/>
        </joint>

    </xacro:macro>
    <!-- END TAXEL MACRO -->

    <!--PALM FRONT TAXELS MACRO-->
    <xacro:macro name="Palm_Front_Taxels" 
    params="reference_taxel_name taxel_sphere_radius">
    <!-- Taxel 1-->
        <xacro:taxel 
        count = "1"
        ref_taxel_name = "${reference_taxel_name}" 
        sphere_radius =  "${taxel_sphere_radius}"
        origin_xyz = "0 -0.015 0"
        origin_rpy = "0 0 0"
        />
    <!-- Taxel 2-->
        <xacro:taxel 
        count = "2"
        ref_taxel_name = "${reference_taxel_name}" 
        sphere_radius =  "${taxel_sphere_radius}"
        origin_xyz = "0 -0.015 0"
        origin_rpy = "0 0 0"
        />
    <!-- Taxel 3-->
        <xacro:taxel 
        count = "3"
        ref_taxel_name = "${reference_taxel_name}" 
        sphere_radius =  "${taxel_sphere_radius}"
        origin_xyz = "0 -0.015 0"
        origin_rpy = "0 0 0"
        />
    <!-- Taxel 4-->
        <xacro:taxel 
        count = "4"
        ref_taxel_name = "${reference_taxel_name}" 
        sphere_radius =  "${taxel_sphere_radius}"
        origin_xyz = "0 -0.015 0"
        origin_rpy = "0 0 0"
        />
    <!-- Taxel 5-->
        <xacro:taxel 
        count = "5"
        ref_taxel_name = "${reference_taxel_name}" 
        sphere_radius =  "${taxel_sphere_radius}"
        origin_xyz = "0 -0.015 0"
        origin_rpy = "0 0 0"
        />
    <!-- Taxel 6-->
        <xacro:taxel 
        count = "6"
        ref_taxel_name = "${reference_taxel_name}" 
        sphere_radius =  "${taxel_sphere_radius}"
        origin_xyz = "0 -0.015 0"
        origin_rpy = "0 0 0"
        />
    <!-- Taxel 7-->
        <xacro:taxel 
        count = "7"
        ref_taxel_name = "${reference_taxel_name}" 
        sphere_radius =  "${taxel_sphere_radius}"
        origin_xyz = "0 -0.015 0"
        origin_rpy = "0 0 0"
        />
    <!-- New Row-->
    <!-- Taxel 8-->
        <xacro:taxel 
        count = "8"
        ref_taxel_name = "${reference_taxel_name}" 
        sphere_radius =  "${taxel_sphere_radius}"
        origin_xyz = "0 0 -0.015"
        origin_rpy = "0 0 0"
        />
    <!-- Taxel 9-->
        <xacro:taxel 
        count = "9"
        ref_taxel_name = "${reference_taxel_name}" 
        sphere_radius =  "${taxel_sphere_radius}"
        origin_xyz = "0 0.015 0"
        origin_rpy = "0 0 0"
        />
    <!-- Taxel 10-->
        <xacro:taxel 
        count = "10"
        ref_taxel_name = "${reference_taxel_name}" 
        sphere_radius =  "${taxel_sphere_radius}"
        origin_xyz = "0 0.015 0"
        origin_rpy = "0 0 0"
        />
    <!-- Taxel 11-->
        <xacro:taxel 
        count = "11"
        ref_taxel_name = "${reference_taxel_name}" 
        sphere_radius =  "${taxel_sphere_radius}"
        origin_xyz = "0 0.015 0"
        origin_rpy = "0 0 0"
        />
    <!-- Taxel 12-->
        <xacro:taxel 
        count = "12"
        ref_taxel_name = "${reference_taxel_name}" 
        sphere_radius =  "${taxel_sphere_radius}"
        origin_xyz = "0 0.015 0"
        origin_rpy = "0 0 0"
        />
    <!-- Taxel 13-->
        <xacro:taxel 
        count = "13"
        ref_taxel_name = "${reference_taxel_name}" 
        sphere_radius =  "${taxel_sphere_radius}"
        origin_xyz = "0 0.015 0"
        origin_rpy = "0 0 0"
        />
    <!-- Taxel 14-->
        <xacro:taxel 
        count = "14"
        ref_taxel_name = "${reference_taxel_name}" 
        sphere_radius =  "${taxel_sphere_radius}"
        origin_xyz = "0 0.015 0"
        origin_rpy = "0 0 0"
        />
    <!-- Taxel 15-->
        <xacro:taxel 
        count = "15"
        ref_taxel_name = "${reference_taxel_name}" 
        sphere_radius =  "${taxel_sphere_radius}"
        origin_xyz = "0 0.015 0"
        origin_rpy = "0 0 0"
        />
    <!-- New Row-->
    <!-- Taxel 16-->
        <xacro:taxel 
        count = "16"
        ref_taxel_name = "${reference_taxel_name}" 
        sphere_radius =  "${taxel_sphere_radius}"
        origin_xyz = "0 -0.06 -0.015"
        origin_rpy = "0 0 0"
        />
    <!-- Taxel 17-->
        <xacro:taxel 
        count = "17"
        ref_taxel_name = "${reference_taxel_name}" 
        sphere_radius =  "${taxel_sphere_radius}"
        origin_xyz = "0 -0.015 0"
        origin_rpy = "0 0 0"
        />
    <!-- Taxel 18-->
        <xacro:taxel 
        count = "18"
        ref_taxel_name = "${reference_taxel_name}" 
        sphere_radius =  "${taxel_sphere_radius}"
        origin_xyz = "0 -0.015 0"
        origin_rpy = "0 0 0"
        />
    <!-- Taxel 19-->
        <xacro:taxel 
        count = "19"
        ref_taxel_name = "${reference_taxel_name}" 
        sphere_radius =  "${taxel_sphere_radius}"
        origin_xyz = "0 -0.015 0"
        origin_rpy = "0 0 0"
        />
    </xacro:macro>
    <!--END PALM FRONT TAXELS MACRO-->

    <!--PALM BACK TAXELS MACRO-->
    <xacro:macro name="Palm_Back_Taxels" 
    params="reference_taxel_name taxel_sphere_radius">
    <!-- Taxel 1-->
        <xacro:taxel 
        count = "1"
        ref_taxel_name = "${reference_taxel_name}" 
        sphere_radius =  "${taxel_sphere_radius}"
        origin_xyz = "0 -0.015 0"
        origin_rpy = "0 0 0"
        />
    <!-- Taxel 2-->
        <xacro:taxel 
        count = "2"
        ref_taxel_name = "${reference_taxel_name}" 
        sphere_radius =  "${taxel_sphere_radius}"
        origin_xyz = "0 -0.015 0"
        origin_rpy = "0 0 0"
        />
    <!-- Taxel 3-->
        <xacro:taxel 
        count = "3"
        ref_taxel_name = "${reference_taxel_name}" 
        sphere_radius =  "${taxel_sphere_radius}"
        origin_xyz = "0 -0.015 0"
        origin_rpy = "0 0 0"
        />
    <!-- Taxel 4-->
        <xacro:taxel 
        count = "4"
        ref_taxel_name = "${reference_taxel_name}" 
        sphere_radius =  "${taxel_sphere_radius}"
        origin_xyz = "0 -0.015 0"
        origin_rpy = "0 0 0"
        />
    <!-- New Row-->
    <!-- Taxel 5-->
        <xacro:taxel 
        count = "5"
        ref_taxel_name = "${reference_taxel_name}" 
        sphere_radius =  "${taxel_sphere_radius}"
        origin_xyz = "0 0 -0.015"
        origin_rpy = "0 0 0"
        />
    <!-- Taxel 6-->
        <xacro:taxel 
        count = "6"
        ref_taxel_name = "${reference_taxel_name}" 
        sphere_radius =  "${taxel_sphere_radius}"
        origin_xyz = "0 0.015 0"
        origin_rpy = "0 0 0"
        />
    <!-- Taxel 7-->
        <xacro:taxel 
        count = "7"
        ref_taxel_name = "${reference_taxel_name}" 
        sphere_radius =  "${taxel_sphere_radius}"
        origin_xyz = "0 0.015 0"
        origin_rpy = "0 0 0"
        />
    <!-- Taxel 8-->
        <xacro:taxel 
        count = "8"
        ref_taxel_name = "${reference_taxel_name}" 
        sphere_radius =  "${taxel_sphere_radius}"
        origin_xyz = "0 0.015 0"
        origin_rpy = "0 0 0"
        />
    <!-- Taxel 9-->
        <xacro:taxel 
        count = "9"
        ref_taxel_name = "${reference_taxel_name}" 
        sphere_radius =  "${taxel_sphere_radius}"
        origin_xyz = "0 0.015 0"
        origin_rpy = "0 0 0"
        />
    <!-- New Row-->
    <!-- Taxel 10-->
        <xacro:taxel 
        count = "10"
        ref_taxel_name = "${reference_taxel_name}" 
        sphere_radius =  "${taxel_sphere_radius}"
        origin_xyz = "0 0 -0.015"
        origin_rpy = "0 0 0"
        />
    <!-- Taxel 11-->
        <xacro:taxel 
        count = "11"
        ref_taxel_name = "${reference_taxel_name}" 
        sphere_radius =  "${taxel_sphere_radius}"
        origin_xyz = "0 -0.015 0"
        origin_rpy = "0 0 0"
        />
    <!-- Taxel 12-->
        <xacro:taxel 
        count = "12"
        ref_taxel_name = "${reference_taxel_name}" 
        sphere_radius =  "${taxel_sphere_radius}"
        origin_xyz = "0 -0.015 0"
        origin_rpy = "0 0 0"
        />
    <!-- Taxel 13-->
        <xacro:taxel 
        count = "13"
        ref_taxel_name = "${reference_taxel_name}" 
        sphere_radius =  "${taxel_sphere_radius}"
        origin_xyz = "0 -0.015 0"
        origin_rpy = "0 0 0"
        />
    <!-- Taxel 14-->
        <xacro:taxel 
        count = "14"
        ref_taxel_name = "${reference_taxel_name}" 
        sphere_radius =  "${taxel_sphere_radius}"
        origin_xyz = "0 -0.015 0"
        origin_rpy = "0 0 0"
        />
    <!-- New Row-->
    <!-- Taxel 15-->
        <xacro:taxel 
        count = "15"
        ref_taxel_name = "${reference_taxel_name}" 
        sphere_radius =  "${taxel_sphere_radius}"
        origin_xyz = "0 0 -0.015"
        origin_rpy = "0 0 0"
        />
    <!-- Taxel 16-->
        <xacro:taxel 
        count = "16"
        ref_taxel_name = "${reference_taxel_name}" 
        sphere_radius =  "${taxel_sphere_radius}"
        origin_xyz = "0 0.015 0"
        origin_rpy = "0 0 0"
        />
    <!-- Taxel 17-->
        <xacro:taxel 
        count = "17"
        ref_taxel_name = "${reference_taxel_name}" 
        sphere_radius =  "${taxel_sphere_radius}"
        origin_xyz = "0 0.015 0"
        origin_rpy = "0 0 0"
        />
    <!-- Taxel 18-->
        <xacro:taxel 
        count = "18"
        ref_taxel_name = "${reference_taxel_name}" 
        sphere_radius =  "${taxel_sphere_radius}"
        origin_xyz = "0 0.015 0"
        origin_rpy = "0 0 0"
        />
    <!-- Taxel 19-->
        <xacro:taxel 
        count = "19"
        ref_taxel_name = "${reference_taxel_name}" 
        sphere_radius =  "${taxel_sphere_radius}"
        origin_xyz = "0 0.015 0"
        origin_rpy = "0 0 0"
        />
    <!-- New Row-->
    <!-- Taxel 20-->
        <xacro:taxel 
        count = "20"
        ref_taxel_name = "${reference_taxel_name}" 
        sphere_radius =  "${taxel_sphere_radius}"
        origin_xyz = "0 0 -0.015"
        origin_rpy = "0 0 0"
        />
    <!-- Taxel 21-->
        <xacro:taxel 
        count = "21"
        ref_taxel_name = "${reference_taxel_name}" 
        sphere_radius =  "${taxel_sphere_radius}"
        origin_xyz = "0 -0.015 0"
        origin_rpy = "0 0 0"
        />
    <!-- Taxel 22-->
        <xacro:taxel 
        count = "22"
        ref_taxel_name = "${reference_taxel_name}" 
        sphere_radius =  "${taxel_sphere_radius}"
        origin_xyz = "0 -0.015 0"
        origin_rpy = "0 0 0"
        />
    <!-- Taxel 23-->
        <xacro:taxel 
        count = "23"
        ref_taxel_name = "${reference_taxel_name}" 
        sphere_radius =  "${taxel_sphere_radius}"
        origin_xyz = "0 -0.015 0"
        origin_rpy = "0 0 0"
        />
    <!-- Taxel 24-->
        <xacro:taxel 
        count = "24"
        ref_taxel_name = "${reference_taxel_name}" 
        sphere_radius =  "${taxel_sphere_radius}"
        origin_xyz = "0 -0.015 0"
        origin_rpy = "0 0 0"
        />

    </xacro:macro>
    <!--END PALM FRONT TAXELS MACRO-->

    <!--PART A BACK TAXELS MACRO-->
    <xacro:macro name="PartA_Back_Taxels" 
    params="reference_taxel_name taxel_sphere_radius">
    <!-- Taxel 1-->
        <xacro:taxel 
        count = "1"
        ref_taxel_name = "${reference_taxel_name}" 
        sphere_radius =  "${taxel_sphere_radius}"
        origin_xyz = "0 0 0.01"
        origin_rpy = "0 0 0"
        />
    <!-- Taxel 2-->
        <xacro:taxel 
        count = "2"
        ref_taxel_name = "${reference_taxel_name}" 
        sphere_radius =  "${taxel_sphere_radius}"
        origin_xyz = "0 0 0.01"
        origin_rpy = "0 0 0"
        />
    <!-- Taxel 3-->
        <xacro:taxel 
        count = "3"
        ref_taxel_name = "${reference_taxel_name}" 
        sphere_radius =  "${taxel_sphere_radius}"
        origin_xyz = "0 0 0.01"
        origin_rpy = "0 0 0"
        />
    <!-- Taxel 4-->
        <xacro:taxel 
        count = "4"
        ref_taxel_name = "${reference_taxel_name}" 
        sphere_radius =  "${taxel_sphere_radius}"
        origin_xyz = "0 0 0.01"
        origin_rpy = "0 0 0"
        />
    <!-- New Row-->
    <!-- Taxel 5-->
        <xacro:taxel 
        count = "5"
        ref_taxel_name = "${reference_taxel_name}" 
        sphere_radius =  "${taxel_sphere_radius}"
        origin_xyz = "0 -0.01 0"
        origin_rpy = "0 0 0"
        />
    <!-- Taxel 6-->
        <xacro:taxel 
        count = "6"
        ref_taxel_name = "${reference_taxel_name}" 
        sphere_radius =  "${taxel_sphere_radius}"
        origin_xyz = "0 0 -0.01"
        origin_rpy = "0 0 0"
        />
    <!-- Taxel 7-->
        <xacro:taxel 
        count = "7"
        ref_taxel_name = "${reference_taxel_name}" 
        sphere_radius =  "${taxel_sphere_radius}"
        origin_xyz = "0 0 -0.01"
        origin_rpy = "0 0 0"
        />
    <!-- Taxel 8-->
        <xacro:taxel 
        count = "8"
        ref_taxel_name = "${reference_taxel_name}" 
        sphere_radius =  "${taxel_sphere_radius}"
        origin_xyz = "0 0 -0.01"
        origin_rpy = "0 0 0"
        />
    <!-- Taxel 9-->
        <xacro:taxel 
        count = "9"
        ref_taxel_name = "${reference_taxel_name}" 
        sphere_radius =  "${taxel_sphere_radius}"
        origin_xyz = "0 0 -0.01"
        origin_rpy = "0 0 0"
        />
    <!-- New Row-->
    <!-- Taxel 10-->
        <xacro:taxel 
        count = "10"
        ref_taxel_name = "${reference_taxel_name}" 
        sphere_radius =  "${taxel_sphere_radius}"
        origin_xyz = "0 -0.01 0"
        origin_rpy = "0 0 0"
        />
    <!-- Taxel 11-->
        <xacro:taxel 
        count = "11"
        ref_taxel_name = "${reference_taxel_name}" 
        sphere_radius =  "${taxel_sphere_radius}"
        origin_xyz = "0 0 0.01"
        origin_rpy = "0 0 0"
        />
    <!-- Taxel 12-->
        <xacro:taxel 
        count = "12"
        ref_taxel_name = "${reference_taxel_name}" 
        sphere_radius =  "${taxel_sphere_radius}"
        origin_xyz = "0 0 0.01"
        origin_rpy = "0 0 0"
        />
    <!-- Taxel 13-->
        <xacro:taxel 
        count = "13"
        ref_taxel_name = "${reference_taxel_name}" 
        sphere_radius =  "${taxel_sphere_radius}"
        origin_xyz = "0 0 0.01"
        origin_rpy = "0 0 0"
        />
    <!-- Taxel 14-->
        <xacro:taxel 
        count = "14"
        ref_taxel_name = "${reference_taxel_name}" 
        sphere_radius =  "${taxel_sphere_radius}"
        origin_xyz = "0 0 0.01"
        origin_rpy = "0 0 0"
        />
    </xacro:macro>
    <!--END PART A BACK TAXELS MACRO-->

    <!--PART AB FRONT FINGERBACK TAXELS MACRO-->
    <xacro:macro name="PartAB_Front_FingerBack_Taxels" 
    params="reference_taxel_name taxel_sphere_radius">
    <!-- Taxel 1-->
        <xacro:taxel 
        count = "1"
        ref_taxel_name = "${reference_taxel_name}" 
        sphere_radius =  "${taxel_sphere_radius}"
        origin_xyz = "0 0 0.009"
        origin_rpy = "0 0 0"
        />
    <!-- Taxel 2-->
        <xacro:taxel 
        count = "2"
        ref_taxel_name = "${reference_taxel_name}" 
        sphere_radius =  "${taxel_sphere_radius}"
        origin_xyz = "0 0 0.009"
        origin_rpy = "0 0 0"
        />
    <!-- New Row-->
    <!-- Taxel 3-->
        <xacro:taxel 
        count = "3"
        ref_taxel_name = "${reference_taxel_name}" 
        sphere_radius =  "${taxel_sphere_radius}"
        origin_xyz = "0 0.009 0"
        origin_rpy = "0 0 0"
        />
    <!-- Taxel 4-->
        <xacro:taxel 
        count = "4"
        ref_taxel_name = "${reference_taxel_name}" 
        sphere_radius =  "${taxel_sphere_radius}"
        origin_xyz = "0 0 -0.009"
        origin_rpy = "0 0 0"
        />
    <!-- Taxel 5-->
        <xacro:taxel 
        count = "5"
        ref_taxel_name = "${reference_taxel_name}" 
        sphere_radius =  "${taxel_sphere_radius}"
        origin_xyz = "0 0 -0.009"
        origin_rpy = "0 0 0"
        />
    </xacro:macro>

    <!--END PART AB FRONT FINGERBACK TAXELS MACRO-->

    <!--PART AB FRONT FINGERFRONT UPPER TAXELS MACRO-->
    <xacro:macro name="PartAB_Front_FingerFront_Upper_Taxels" 
    params="reference_taxel_name taxel_sphere_radius">
    <!-- Taxel 1-->
        <xacro:taxel 
        count = "1"
        ref_taxel_name = "${reference_taxel_name}" 
        sphere_radius =  "${taxel_sphere_radius}"
        origin_xyz = "0 0 -0.009"
        origin_rpy = "0 0 0"
        />
    <!-- Taxel 2-->
        <xacro:taxel 
        count = "2"
        ref_taxel_name = "${reference_taxel_name}" 
        sphere_radius =  "${taxel_sphere_radius}"
        origin_xyz = "0 0 -0.009"
        origin_rpy = "0 0 0"
        />
    <!-- New Row-->
    <!-- Taxel 3-->
        <xacro:taxel 
        count = "3"
        ref_taxel_name = "${reference_taxel_name}" 
        sphere_radius =  "${taxel_sphere_radius}"
        origin_xyz = "0 0.009 0"
        origin_rpy = "0 0 0"
        />
    <!-- Taxel 4-->
        <xacro:taxel 
        count = "4"
        ref_taxel_name = "${reference_taxel_name}" 
        sphere_radius =  "${taxel_sphere_radius}"
        origin_xyz = "0 0 0.009"
        origin_rpy = "0 0 0"
        />
    <!-- Taxel 5-->
        <xacro:taxel 
        count = "5"
        ref_taxel_name = "${reference_taxel_name}" 
        sphere_radius =  "${taxel_sphere_radius}"
        origin_xyz = "0 0 0.009"
        origin_rpy = "0 0 0"
        />
    </xacro:macro>

    <!--END PART AB FRONT FINGERFRONT UPPER TAXELS MACRO-->
    
    <!--PART AB FRONT FINGERFRONT BOTTOM TAXELS MACRO-->
    <xacro:macro name="PartAB_Front_FingerFront_Bottom_Taxels" 
    params="reference_taxel_name taxel_sphere_radius">
    <!-- Taxel 1-->
        <xacro:taxel 
        count = "1"
        ref_taxel_name = "${reference_taxel_name}" 
        sphere_radius =  "${taxel_sphere_radius}"
        origin_xyz = "0 0 -0.009"
        origin_rpy = "0 0 0"
        />
    <!-- Taxel 2-->
        <xacro:taxel 
        count = "2"
        ref_taxel_name = "${reference_taxel_name}" 
        sphere_radius =  "${taxel_sphere_radius}"
        origin_xyz = "0 0 -0.009"
        origin_rpy = "0 0 0"
        />
    <!-- New Row-->
    <!-- Taxel 3-->
        <xacro:taxel 
        count = "3"
        ref_taxel_name = "${reference_taxel_name}" 
        sphere_radius =  "${taxel_sphere_radius}"
        origin_xyz = "0 -0.009 0"
        origin_rpy = "0 0 0"
        />
    <!-- Taxel 4-->
        <xacro:taxel 
        count = "4"
        ref_taxel_name = "${reference_taxel_name}" 
        sphere_radius =  "${taxel_sphere_radius}"
        origin_xyz = "0 0 0.009"
        origin_rpy = "0 0 0"
        />
    <!-- Taxel 5-->
        <xacro:taxel 
        count = "5"
        ref_taxel_name = "${reference_taxel_name}" 
        sphere_radius =  "${taxel_sphere_radius}"
        origin_xyz = "0 0 0.009"
        origin_rpy = "0 0 0"
        />
    </xacro:macro>

    <!--END PART AB FRONT FINGERFRONT BOTTOM TAXELS MACRO-->

    <!--PART AB FRONT THUMBBACK LOWER TAXELS MACRO-->
    <xacro:macro name="PartAB_Front_ThumbBack_Lower_Taxels" 
    params="reference_taxel_name taxel_sphere_radius">
    <!-- Taxel 1-->
        <xacro:taxel 
        count = "1"
        ref_taxel_name = "${reference_taxel_name}" 
        sphere_radius =  "${taxel_sphere_radius}"
        origin_xyz = "0 0 0.009"
        origin_rpy = "0 0 0"
        />
    <!-- Taxel 2-->
        <xacro:taxel 
        count = "2"
        ref_taxel_name = "${reference_taxel_name}" 
        sphere_radius =  "${taxel_sphere_radius}"
        origin_xyz = "0 0 0.009"
        origin_rpy = "0 0 0"
        />
    <!-- New Row-->
    <!-- Taxel 3-->
        <xacro:taxel 
        count = "3"
        ref_taxel_name = "${reference_taxel_name}" 
        sphere_radius =  "${taxel_sphere_radius}"
        origin_xyz = "0 -0.009 0"
        origin_rpy = "0 0 0"
        />
    <!-- Taxel 4-->
        <xacro:taxel 
        count = "4"
        ref_taxel_name = "${reference_taxel_name}" 
        sphere_radius =  "${taxel_sphere_radius}"
        origin_xyz = "0 0 -0.009"
        origin_rpy = "0 0 0"
        />
    <!-- Taxel 5-->
        <xacro:taxel 
        count = "5"
        ref_taxel_name = "${reference_taxel_name}" 
        sphere_radius =  "${taxel_sphere_radius}"
        origin_xyz = "0 0 -0.009"
        origin_rpy = "0 0 0"
        />
    </xacro:macro>

    <!--END PART AB FRONT THUMBBACK LOWER TAXELS MACRO-->

    <!--PART AB FRONT THUMBBACK UPPER TAXELS MACRO-->
    <xacro:macro name="PartAB_Front_ThumbBack_Upper_Taxels" 
    params="reference_taxel_name taxel_sphere_radius">
    <!-- Taxel 1-->
        <xacro:taxel 
        count = "1"
        ref_taxel_name = "${reference_taxel_name}" 
        sphere_radius =  "${taxel_sphere_radius}"
        origin_xyz = "0 0 0.009"
        origin_rpy = "0 0 0"
        />
    <!-- Taxel 2-->
        <xacro:taxel 
        count = "2"
        ref_taxel_name = "${reference_taxel_name}" 
        sphere_radius =  "${taxel_sphere_radius}"
        origin_xyz = "0 0 0.009"
        origin_rpy = "0 0 0"
        />
    <!-- New Row-->
    <!-- Taxel 3-->
        <xacro:taxel 
        count = "3"
        ref_taxel_name = "${reference_taxel_name}" 
        sphere_radius =  "${taxel_sphere_radius}"
        origin_xyz = "0 -0.009 0"
        origin_rpy = "0 0 0"
        />
    <!-- Taxel 4-->
        <xacro:taxel 
        count = "4"
        ref_taxel_name = "${reference_taxel_name}" 
        sphere_radius =  "${taxel_sphere_radius}"
        origin_xyz = "0 0 -0.009"
        origin_rpy = "0 0 0"
        />
    <!-- Taxel 5-->
        <xacro:taxel 
        count = "5"
        ref_taxel_name = "${reference_taxel_name}" 
        sphere_radius =  "${taxel_sphere_radius}"
        origin_xyz = "0 0 -0.009"
        origin_rpy = "0 0 0"
        />
    </xacro:macro>

    <!--END PART AB FRONT THUMBBACK UPPER TAXELS MACRO-->

    <!--PART AB FRONT TUMBFRONT LOWER TAXELS MACRO-->
    <xacro:macro name="PartAB_Front_ThumbFront_Lower_Taxels" 
    params="reference_taxel_name taxel_sphere_radius">
    <!-- Taxel 1-->
        <xacro:taxel 
        count = "1"
        ref_taxel_name = "${reference_taxel_name}" 
        sphere_radius =  "${taxel_sphere_radius}"
        origin_xyz = "0 0 0.009"
        origin_rpy = "0 0 0"
        />
    <!-- Taxel 2-->
        <xacro:taxel 
        count = "2"
        ref_taxel_name = "${reference_taxel_name}" 
        sphere_radius =  "${taxel_sphere_radius}"
        origin_xyz = "0 0 0.009"
        origin_rpy = "0 0 0"
        />
    <!-- New Row-->
    <!-- Taxel 3-->
        <xacro:taxel 
        count = "3"
        ref_taxel_name = "${reference_taxel_name}" 
        sphere_radius =  "${taxel_sphere_radius}"
        origin_xyz = "0 -0.009 0"
        origin_rpy = "0 0 0"
        />
    <!-- Taxel 4-->
        <xacro:taxel 
        count = "4"
        ref_taxel_name = "${reference_taxel_name}" 
        sphere_radius =  "${taxel_sphere_radius}"
        origin_xyz = "0 0 -0.009"
        origin_rpy = "0 0 0"
        />
    <!-- Taxel 5-->
        <xacro:taxel 
        count = "5"
        ref_taxel_name = "${reference_taxel_name}" 
        sphere_radius =  "${taxel_sphere_radius}"
        origin_xyz = "0 0 -0.009"
        origin_rpy = "0 0 0"
        />
    </xacro:macro>

    <!--END PART AB FRONT THUMBFRONT LOWER TAXELS MACRO-->

    <!--PART AB FRONT TUMBFRONT UPPER TAXELS MACRO-->
    <xacro:macro name="PartAB_Front_ThumbFront_Upper_Taxels" 
    params="reference_taxel_name taxel_sphere_radius">
    <!-- Taxel 1-->
        <xacro:taxel 
        count = "1"
        ref_taxel_name = "${reference_taxel_name}" 
        sphere_radius =  "${taxel_sphere_radius}"
        origin_xyz = "0 0 0.009"
        origin_rpy = "0 0 0"
        />
    <!-- Taxel 2-->
        <xacro:taxel 
        count = "2"
        ref_taxel_name = "${reference_taxel_name}" 
        sphere_radius =  "${taxel_sphere_radius}"
        origin_xyz = "0 0 0.009"
        origin_rpy = "0 0 0"
        />
    <!-- New Row-->
    <!-- Taxel 3-->
        <xacro:taxel 
        count = "3"
        ref_taxel_name = "${reference_taxel_name}" 
        sphere_radius =  "${taxel_sphere_radius}"
        origin_xyz = "0 -0.009 0"
        origin_rpy = "0 0 0"
        />
    <!-- Taxel 4-->
        <xacro:taxel 
        count = "4"
        ref_taxel_name = "${reference_taxel_name}" 
        sphere_radius =  "${taxel_sphere_radius}"
        origin_xyz = "0 0 -0.009"
        origin_rpy = "0 0 0"
        />
    <!-- Taxel 5-->
        <xacro:taxel 
        count = "5"
        ref_taxel_name = "${reference_taxel_name}" 
        sphere_radius =  "${taxel_sphere_radius}"
        origin_xyz = "0 0 -0.009"
        origin_rpy = "0 0 0"
        />
    </xacro:macro>

    <!--END PART AB FRONT THUMBFRONT UPPER TAXELS MACRO-->


    <!--FINGERTIP INCLINED TAXELS MACRO-->
    <xacro:macro name="Fingertip_Inclined_Taxels" 
    params="reference_taxel_name taxel_sphere_radius">
    <!-- Taxel 1-->
        <xacro:taxel 
        count = "1"
        ref_taxel_name = "${reference_taxel_name}" 
        sphere_radius =  "${taxel_sphere_radius}"
        origin_xyz = "-0.003135 0 0.009496"
        origin_rpy = "0 0 0"
        />
    <!-- Taxel 2-->
        <xacro:taxel 
        count = "2"
        ref_taxel_name = "${reference_taxel_name}" 
        sphere_radius =  "${taxel_sphere_radius}"
        origin_xyz = "-0.003135 0 0.009496"
        origin_rpy = "0 0 0"
        />
    <!-- Taxel 3-->
        <xacro:taxel 
        count = "3"
        ref_taxel_name = "${reference_taxel_name}" 
        sphere_radius =  "${taxel_sphere_radius}"
        origin_xyz = "-0.003135 0 0.009496"
        origin_rpy = "0 0 0"
        />
    <!-- Taxel 4-->
        <xacro:taxel 
        count = "4"
        ref_taxel_name = "${reference_taxel_name}" 
        sphere_radius =  "${taxel_sphere_radius}"
        origin_xyz = "-0.003135 0 0.009496"
        origin_rpy = "0 0 0"
        />
    <!-- New row-->
    <!-- Taxel 5-->
        <xacro:taxel 
        count = "5"
        ref_taxel_name = "${reference_taxel_name}" 
        sphere_radius =  "${taxel_sphere_radius}"
        origin_xyz = "0 -0.01 0"
        origin_rpy = "0 0 0"
        />
    <!-- Taxel 6-->
        <xacro:taxel 
        count = "6"
        ref_taxel_name = "${reference_taxel_name}" 
        sphere_radius =  "${taxel_sphere_radius}"
        origin_xyz = "0.003135 0 -0.009496"
        origin_rpy = "0 0 0"
        />
    <!-- Taxel 7-->
        <xacro:taxel 
        count = "7"
        ref_taxel_name = "${reference_taxel_name}" 
        sphere_radius =  "${taxel_sphere_radius}"
        origin_xyz = "0.003135 0 -0.009496"
        origin_rpy = "0 0 0"
        />
    <!-- Taxel 8-->
        <xacro:taxel 
        count = "8"
        ref_taxel_name = "${reference_taxel_name}" 
        sphere_radius =  "${taxel_sphere_radius}"
        origin_xyz = "0.003135 0 -0.009496"
        origin_rpy = "0 0 0"
        />
    <!-- Taxel 9-->
        <xacro:taxel 
        count = "9"
        ref_taxel_name = "${reference_taxel_name}" 
        sphere_radius =  "${taxel_sphere_radius}"
        origin_xyz = "0.003135 0 -0.009496"
        origin_rpy = "0 0 0"
        />
    </xacro:macro>

    <!--END FINGERTIP INCLINED TAXELS MACRO-->

    <!-- PALM -->
    <link name="palm_link">
        <visual>
            <geometry>
                <mesh filename="package://allegro_hand_description/meshes/base_link.STL"/>
            </geometry>
            <origin rpy="0 0 0" xyz="0 0 0 "/>
            <material name="black">
                <color rgba="0.2 0.2 0.2 1"/>
            </material>
        </visual>

        <collision>
            <origin rpy="0 0 0" xyz="-0.009300 0 -${palm_link_z/2}"/>
            <geometry>
                <box size="0.0408 0.1130 ${palm_link_z}"/>
            </geometry>
        </collision>
        <inertial>
          <origin xyz="0 0 ${palm_link_z/2}" rpy="0 0 0"/>
          <mass value="0.4154"/>
          <inertia
              ixx="1e-4" ixy="0.0" ixz="0.0"
              iyy="1e-4" iyz="0.0"
              izz="1e-4"/>
        </inertial>
    </link>
    <!-- PALM FRONT REFERENCE TAXEL -->
    <!--
    <link name="link_palm_front_taxel_0">
        <visual>
            <geometry>
                <sphere radius="0.0025"/>
            </geometry> 
                <material name="Orange">
                    <color rgba="${255/255} ${108/255} ${10/255} 1.0"/>
                </material>
        </visual>

        <collision>
            <geometry>
                <sphere radius="0.0025"/>
            </geometry>
        </collision>
    </link>

    <joint name="joint_palm_front_taxel_0" type="fixed">
        <parent link="palm_link"/>
        <child link="link_palm_front_taxel_0"/>
        <origin xyz="0.015 0.045 -0.015" rpy="0 0 0"/>
    -->
        <!-- the origin coordinates must be measured-->
    <!--
    </joint>
    -->
<!-- PALM FRONT TAXELS-->   
<!--
    <xacro:Palm_Front_Taxels reference_taxel_name = "link_palm_front_taxel" taxel_sphere_radius = "0.0025"/>
-->
<!-- PALM BACK REFERENCE TAXEL -->
<!--
    <link name="link_palm_back_taxel_0">
        <visual>
            <geometry>
                <sphere radius="0.0025"/>
            </geometry> 
                <material name="Orange">
                    <color rgba="${255/255} ${108/255} ${10/255} 1.0"/>
                </material>
        </visual>

        <collision>
            <geometry>
                <sphere radius="0.0025"/>
            </geometry>
        </collision>
    </link>

    <joint name="joint_palm_back_taxel_0" type="fixed">
        <parent link="palm_link"/>
        <child link="link_palm_back_taxel_0"/>
        <origin xyz="-0.035 0.045 -0.015" rpy="0 0 0"/>
    </joint>
-->
   <!-- PALM BACK TAXELS-->
<!--   
    <xacro:Palm_Back_Taxels reference_taxel_name = "link_palm_back_taxel" taxel_sphere_radius = "0.0025"/>
-->
    <!-- ============================================================================= -->
    <!-- REFERENCE TAXEL MACRO -->
    <xacro:macro name="ref_taxel"
                 params="finger_num finger_part face tip origin_xyz origin_rpy sphere_radius">
            <link name="link_${finger_num*4+finger_part}_${face}${tip}_taxel_0">
            <visual>
                    <geometry>
                        <sphere radius="${sphere_radius}"/>
                    </geometry> 
                    <material name="Green">
                        <color rgba="${90/255} ${108/255} ${10/255} 1.0"/>
                    </material>
            </visual>

            <collision>
                <geometry>
                    <sphere radius="${sphere_radius}"/>
                </geometry>
            </collision>
        </link>

        <joint name="joint_${finger_num*4+finger_part}_${face}${tip}_taxel_0" type="fixed">
            <parent link="link_${finger_num*4+finger_part}${tip}"/>
            <child link="link_${finger_num*4+finger_part}_${face}${tip}_taxel_0"/>
            <origin xyz="${origin_xyz}" rpy="${origin_rpy}"/>
        </joint>

    </xacro:macro>
    <!-- END REFERENCE TAXEL MACRO -->
    <!-- ============================================================================= -->

    <!-- THUMB MACRO -->
    <xacro:macro name="thumb_right"
                 params="finger_num offset_origin_x offset_origin_y offset_origin_z finger_angle_r finger_angle_p finger_angle_y">

        <!-- [LINK 12] -->
        <link name="link_${finger_num*4+0}">
            <visual>
                <geometry>
                    <mesh filename="package://allegro_hand_description/meshes/link_12.0_right.STL"/>
                </geometry>
                <material name="black">
                    <color rgba=".2 .2 .2 1"/>
                </material>
                <origin rpy="${DEG2RAD} 0 0" xyz="0 0 0"/>
            </visual>

            <collision>
                <geometry>
                    <box size="${link0_t_x} ${link0_t_y} ${link0_t_z}"/>
                </geometry>
                <origin rpy="0 0 0" xyz="${-0.0358/2+0.0} ${.018/2} ${.029/2}"/>
            </collision>

            <inertial>
              <mass value="0.0176" />
              <origin xyz="0 0 0" rpy="0 0 0"/>
              <inertia ixx="1.89273333333e-5" ixy="7.16716e-06" ixz="5.35568e-06"
                       iyy="1.43008213333e-05" iyz="6.8068e-06"
                       izz="1.89273333333e-05" />
            </inertial>
        </link>

        <joint name="joint_${finger_num*4+0}_0" type="revolute">
            <axis xyz="-1 0 0"/>
            <limit effort="15" velocity="7"
                   lower="${limit_0_t_low-joint_safety_margin}"
                   upper="${limit_0_t_up-joint_safety_margin}"/>
            <parent link="palm_link"/>
            <child link="link_${finger_num*4+0}"/>
            <origin rpy="${finger_angle_r} ${finger_angle_p} ${finger_angle_y}"
                    xyz="${offset_origin_x} ${offset_origin_y} ${offset_origin_z}"/>
            <dynamics damping="3" friction="10"/>
        </joint>

        <!-- [LINK 13] -->
        <link name="link_${finger_num*4+1}">
            <visual>
                <geometry>
                    <mesh filename="package://allegro_hand_description/meshes/link_13.0.STL"/>
                </geometry>
                <material name="black">
                    <color rgba=".2 .2 .2 1"/>
                </material>
            </visual>

            <collision>
                <geometry>
                    <box size="${links_x} ${links_y} ${link1_t_z}"/>
                </geometry>
                <origin rpy="0 0 0" xyz="0 0 ${link1_t_z/2}"/>
            </collision>

            <inertial>
              <mass value="0.0119" />
              <origin xyz="0 0 0" rpy="0 0 0"/>
              <inertia ixx="4.24250866667e-06" ixy="1.032087e-06" ixz="1.603525e-06"
                       iyy="4.52362633333e-06" iyz="1.44808125e-06"
                       izz="4.24250866667e-06" />
            </inertial>
        </link>

        <joint name="joint_${finger_num*4+1}_0" type="revolute">
            <axis xyz="0 0 1"/>
            <limit effort="15" velocity="7"
                   lower="${limit_1_t_low+joint_safety_margin}"
                   upper="${limit_1_t_up-joint_safety_margin}"/>
            <parent link="link_${finger_num*4+0}"/>
            <child link="link_${finger_num*4+1}"/>
            <origin xyz="-0.027 0.005 0.0399"/>
            <dynamics damping="3" friction="5"/>
        </joint>

        <!-- [LINK 14] -->
        <link name="link_${finger_num*4+2}">
            <visual>
                <geometry>
                    <mesh filename="package://allegro_hand_description/meshes/link_14.0.STL"/>
                </geometry>
                <material name="black">
                </material>
            </visual>

            <collision>
                <geometry>
                    <box size="${links_x} ${links_y} ${link2_t_z}"/>
                </geometry>
                <origin rpy="0 0 0" xyz="0 0 ${link2_t_z/2}"/>
            </collision>

            <inertial>
              <mass value="0.038" />
              <origin xyz="0 0 0" rpy="0 0 0"/>
              <inertia ixx="4.30439933333e-05" ixy="9.57068e-06" ixz="5.1205e-06" iyy="1.44451933333e-05"
                       iyz="1.342825e-05" izz="4.30439933333e-05" />
            </inertial>
        </link>

        <joint name="joint_${finger_num*4+2}_0" type="revolute">
            <axis xyz="0 1 0"/>
            <limit effort="15" velocity="7"
                   lower="${limit_2_t_low+joint_safety_margin}"
                   upper="${limit_2_t_up-joint_safety_margin}"/>
            <parent link="link_${finger_num*4+1}"/>
            <child link="link_${finger_num*4+2}"/>
            <origin xyz="0 0 ${link1_t_z}"/>
            <dynamics damping="3" friction="10"/>
        </joint>
        <!-- Thumb Back Lower Reference Taxel-->
        <!--
        <xacro:ref_taxel
            finger_num = "${finger_num}"
            finger_part = "2"
            face = "back_lower"
            tip = ""
            origin_xyz = "-0.02 0.005 0.002"
            origin_rpy = "0 0 0"
            sphere_radius="0.0025"
        />
        -->
        <!-- Thumb Front Lower Taxels-->
        <!--
        <xacro:PartAB_Front_ThumbBack_Lower_Taxels reference_taxel_name="link_${finger_num*4+2}_back_lower_taxel" taxel_sphere_radius="0.0025" />
        -->
        <!-- Thumb Front Lower Reference Taxel-->
        <!--
        <xacro:ref_taxel
            finger_num = "${finger_num}"
            finger_part = "2"
            face = "front_lower"
            tip = ""
            origin_xyz = "0.02 0.005 0.002"
            origin_rpy = "0 0 0"
            sphere_radius="0.0025"
        />
        -->
        <!-- Thumb Front Lower Taxels-->
        <!--
        <xacro:PartAB_Front_ThumbFront_Lower_Taxels reference_taxel_name="link_${finger_num*4+2}_front_lower_taxel" taxel_sphere_radius="0.0025" />
        -->
        <!-- [LINK 15] -->
        <link name="link_${finger_num*4+3}">
            <visual>
                <geometry>
                    <mesh filename="package://allegro_hand_description/meshes/link_15.0.STL"/>
                </geometry>
                <material name="black">
                </material>
            </visual>

            <collision>
                <geometry>
                    <box size="${links_x} ${links_y} ${link3_t_z-fingerTip_r}"/>
                </geometry>
                <origin rpy="0 0 0" xyz="0 0 ${(link3_t_z-fingerTip_r)/2}"/>
            </collision>

            <inertial>
              <mass value="0.0388" />
              <origin xyz="0 0 0" rpy="0 0 0"/>
              <inertia ixx="3.29223173333e-05" ixy="8.042076e-06" ixz="5.2283e-06"
                       iyy="1.47493026667e-5" iyz="1.1283525e-5"
                       izz="3.29223173333e-05" />
            </inertial>
        </link>

        <joint name="joint_${finger_num*4+3}_0" type="revolute">
            <axis xyz="0 1 0"/>
            <limit effort="15" velocity="7"
                   lower="${limit_3_t_low+joint_safety_margin}"
                   upper="${limit_3_t_up-joint_safety_margin}"/>
            <parent link="link_${finger_num*4+2}"/>
            <child link="link_${finger_num*4+3}"/>
            <origin xyz="0 0 ${link2_t_z}"/>
            <dynamics damping="3" friction="12"/>
        </joint>
        <!-- Thumb Back Upper Reference Taxel-->
        <!--
        <xacro:ref_taxel
            finger_num = "${finger_num}"
            finger_part = "3"
            face = "back_upper"
            tip = ""
            origin_xyz = "-0.02 0.005 0.002"
            origin_rpy = "0 0 0"
            sphere_radius="0.0025"
        />
        -->
        <!-- Thumb Back Upper Taxels-->
        <!--
        <xacro:PartAB_Front_ThumbBack_Upper_Taxels reference_taxel_name="link_${finger_num*4+3}_back_upper_taxel" taxel_sphere_radius="0.0025" />
        -->
        <!-- Thumb Front Upper Reference Taxel-->
        <!--
        <xacro:ref_taxel
            finger_num = "${finger_num}"
            finger_part = "3"
            face = "front_upper"
            tip = ""
            origin_xyz = "0.02 0.005 0.002"
            origin_rpy = "0 0 0"
            sphere_radius="0.0025"
        />
        -->
        <!-- Thumb Front Upper Taxel-->
        <!--
        <xacro:PartAB_Front_ThumbFront_Upper_Taxels reference_taxel_name="link_${finger_num*4+3}_front_upper_taxel" taxel_sphere_radius="0.0025" />
        -->
        <!-- [FINGER TIP] -->
        <link name="link_${finger_num*4+3}_tip">
            <visual>
                <geometry>
                    <mesh filename="package://allegro_hand_description/meshes/link_15.0_tip.STL"/>
                </geometry>
                <material name="white">
                    <color rgba=".9 .9 .9 1"/>
                </material>
            </visual>

            <collision>
                <geometry>
                    <sphere radius="${fingerTip_r}"/>
                </geometry>
                <origin rpy="0 0 0" xyz="0 0 0"/>
            </collision>

            <inertial>
              <mass value="0.0168" />
              <origin xyz="0 0 0" rpy="0 0 0"/>
              <inertia ixx="9.68e-07" ixy="0" ixz="0"
                       iyy="9.68e-07" iyz="0"
                       izz="9.68e-07" />
            </inertial>
        </link>

        <joint name="joint_${finger_num*4+3}_tip" type="fixed">
            <parent link="link_${finger_num*4+3}"/>
            <child link="link_${finger_num*4+3}_tip"/>
            <origin rpy="0 0 0" xyz="0 0 ${link3_t_z-fingerTip_r}"/>
        </joint>
    <!-- FINGERTIP INCLINED PORTION REFERENCE TAXEL -->
    <!--
        <xacro:ref_taxel
            finger_num = "${finger_num}"
            finger_part = "3"
            face = "wedge"
            tip = "_tip"
            origin_xyz = "0.025 0.005 0"
            origin_rpy = "0 0 0"
            sphere_radius="0.0025"
        />
    -->
    <!-- FINGERTIP INCLINED TAXELS -->
    <!--
        <xacro:Fingertip_Inclined_Taxels reference_taxel_name = "link_${finger_num*4+3}_wedge_tip_taxel" taxel_sphere_radius = "0.0025"/>
    -->
    <!-- FINGERTIP FLAT TOP PORTION REFERENCE TAXEL (P.S. No macro is used here in order to index the taxels on the fingetip in a continuous manner)-->
    <!--
        <link name="link_${finger_num*4+3}_wedge_tip_taxel_10">
        <visual>
            <geometry>
                <sphere radius="0.0025"/>
            </geometry> 
            <material name="Orange">
                <color rgba="${255/255} ${108/255} ${10/255} 1.0"/>
            </material>
        </visual>

        <collision>
            <geometry>
                <sphere radius="0.0025"/>
            </geometry>
        </collision>
        </link>

        <joint name="joint_${finger_num*4+3}_wedge_tip_taxel_10" type="fixed">
            <parent link="link_${finger_num*4+3}_tip"/>
            <child link="link_${finger_num*4+3}_wedge_tip_taxel_10"/>
            <origin xyz="0.007 0.005 0.05" rpy="0 0 0"/>
        </joint>
    -->
    <!-- FINGERTIP FLAT TOP TAXELS (P.S. No macro is used here in order to index the taxels on the fingertip in a continuous manner)-->
    <!-- Taxel 1-->
    <!--
        <xacro:taxel 
        count = "11"
        ref_taxel_name = "link_${finger_num*4+3}_wedge_tip_taxel" 
        sphere_radius =  "0.0025"
        origin_xyz = "-0.01 0 0"
        origin_rpy = "0 0 0"
        />
    -->
    <!-- New Row-->
    <!-- Taxel 2-->
    <!--
        <xacro:taxel 
        count = "12"
        ref_taxel_name = "link_${finger_num*4+3}_wedge_tip_taxel" 
        sphere_radius =  "0.0025"
        origin_xyz = "0 -0.01 0"
        origin_rpy = "0 0 0"
        />
    -->
    <!-- Taxel 3-->
    <!--
        <xacro:taxel 
        count = "13"
        ref_taxel_name = "link_${finger_num*4+3}_wedge_tip_taxel" 
        sphere_radius =  "0.0025"
        origin_xyz = "0.01 0 0"
        origin_rpy = "0 0 0"
        />
    -->
         
    <!-- FINGERTIP STRAIGHT PORTION REFERENCE TAXEL (P.S. No macro is used here in order to index the taxels on the fingetip in a continuous manner)-->
        <!--
        <link name="link_${finger_num*4+3}_wedge_tip_taxel_14">
        <visual>
            <geometry>
                <sphere radius="0.0025"/>
            </geometry> 
            <material name="Orange">
                <color rgba="${255/255} ${108/255} ${10/255} 1.0"/>
            </material>
        </visual>

        <collision>
            <geometry>
                <sphere radius="0.0025"/>
            </geometry>
        </collision>
        </link>

        <joint name="joint_${finger_num*4+3}_wedge_tip_taxel_14" type="fixed">
            <parent link="link_${finger_num*4+3}_tip"/>
            <child link="link_${finger_num*4+3}_wedge_tip_taxel_14"/>
            <origin xyz="-0.02 0.005 0.02" rpy="0 0 0"/>
        </joint>
        -->
    <!--FINGERTIP STRAIGHT PORTION TAXELS (P.S. No macro is used here in order to index the taxels on the fingertip in a continuous manner)-->

    <!-- Taxel 1-->
    <!--
        <xacro:taxel 
        count = "15"
        ref_taxel_name = "link_${finger_num*4+3}_wedge_tip_taxel" 
        sphere_radius =  "0.0025"
        origin_xyz = "0 0 -0.009"
        origin_rpy = "0 0 0"
        />
    -->
    <!-- Taxel 2-->
    <!--
        <xacro:taxel 
        count = "16"
        ref_taxel_name = "link_${finger_num*4+3}_wedge_tip_taxel" 
        sphere_radius =  "0.0025"
        origin_xyz = "0 0 -0.009"
        origin_rpy = "0 0 0"
        />
    -->
    <!-- New Row-->
    <!-- Taxel 3-->
    <!--
        <xacro:taxel 
        count = "17"
        ref_taxel_name = "link_${finger_num*4+3}_wedge_tip_taxel" 
        sphere_radius =  "0.0025"
        origin_xyz = "0 -0.009 0"
        origin_rpy = "0 0 0"
        />
    -->
    <!-- Taxel 4-->
    <!--
        <xacro:taxel 
        count = "18"
        ref_taxel_name = "link_${finger_num*4+3}_wedge_tip_taxel" 
        sphere_radius =  "0.0025"
        origin_xyz = "0 0 0.009"
        origin_rpy = "0 0 0"
        />
    -->
    <!-- Taxel 5-->
    <!--
        <xacro:taxel 
        count = "19"
        ref_taxel_name = "link_${finger_num*4+3}_wedge_tip_taxel" 
        sphere_radius =  "0.0025"
        origin_xyz = "0 0 0.009"
        origin_rpy = "0 0 0"
        />
    -->
    
    </xacro:macro>
    <!-- END THUMB MACRO -->
    <!-- THUMB -->
    <xacro:thumb_right
            finger_num="3"
            offset_origin_x="-0.0182"
            offset_origin_y="0.019333"
            offset_origin_z="-0.045987"
            finger_angle_r="0"
            finger_angle_p="-${95*DEG2RAD}"
            finger_angle_y="-${90*DEG2RAD}"
            />

    <!-- THREE FINGER MACRO -->
    <xacro:macro name="finger"
                 params="finger_num offset_origin_x offset_origin_y offset_origin_z finger_angle_r">

        <!-- [LINK 0, 4, 8] -->
        <link name="link_${finger_num*4+0}">
            <visual>
                <geometry>
                    <mesh filename="package://allegro_hand_description/meshes/link_0.0.STL"/>
                </geometry>
                <material name="black"/>
            </visual>

            <collision>
                <geometry>
                    <box size="${links_x} ${links_y} ${link0_z}"/>
                </geometry>
                <origin rpy="0 0 0" xyz="0 0 ${link0_z/2}"/>
            </collision>

            <inertial>
              <mass value="0.0119" />
              <origin xyz="0 0 0" rpy="0 0 0"/>
              <inertia ixx="1.01666658333e-06" ixy="0.0" ixz="0.0"
                       iyy="6.47677333333e-07" iyz="0.0"
                       izz="1.01666658333e-06" />
            </inertial>
        </link>

        <joint name="joint_${finger_num*4+0}_0" type="revolute">
            <axis xyz="0 0 1"/>
            <limit effort="15" velocity="7"
                   lower="${limit_0_low+joint_safety_margin}"
                   upper="${limit_0_up-joint_safety_margin}"/>
            <parent link="palm_link"/>
            <child link="link_${finger_num*4+0}"/>
            <origin rpy="${finger_angle_r} 0 0"
                    xyz="${offset_origin_x} ${offset_origin_y} ${offset_origin_z}"/>
            <dynamics damping="3" friction="10"/>
        </joint>

        <!-- [LINK 1, 5, 9] -->
        <link name="link_${finger_num*4+1}">
            <visual>
                <geometry>
                    <mesh filename="package://allegro_hand_description/meshes/link_1.0.STL"/>
                </geometry>
                <material name="black"/>
            </visual>

            <collision>
                <geometry>
                    <box size="${links_x} ${links_y} ${link1_z}"/>
                </geometry>
                <origin rpy="0 0 0" xyz="0 0 ${link1_z/2}"/>
            </collision>
            <inertial>
              <mass value="0.065" />
              <origin xyz="0 0 0" rpy="0 0 0"/>
              <inertia ixx="7.95654166667e-05" ixy="1.7199e-05" ixz="8.75875e-06"
                       iyy="2.47088833333e-05" iyz="2.413125e-05"
                       izz="7.95654166667e-05" />
            </inertial>
        </link>

        <joint name="joint_${finger_num*4+1}_0" type="revolute">
            <limit effort="15" velocity="7"
                   lower="${limit_1_low+joint_safety_margin}"
                   upper="${limit_1_up-joint_safety_margin}"/>
            <axis xyz="0 1 0"/>
            <parent link="link_${finger_num*4+0}"/>
            <child link="link_${finger_num*4+1}"/>
            <origin xyz="0 0 ${link0_z}"/>
            <dynamics damping="3" friction="5"/>
        </joint>
    <!-- FRONT TAXEL (LOWER) -->
    <!--
        <xacro:ref_taxel
            finger_num = "${finger_num}"
            finger_part = "1"
            face = "front_lower"
            tip = ""
            origin_xyz = "0.02 0.005 0.018"
            origin_rpy = "0 0 0"
            sphere_radius="0.0025"
        />
    -->
    <!-- Part A/B Front Taxels -->
    <!--
        <xacro:PartAB_Front_FingerFront_Bottom_Taxels reference_taxel_name = "link_${finger_num*4+1}_front_lower_taxel" taxel_sphere_radius = "0.0025"/>
    -->
    <!-- BACK TAXEL -->
    <!--
        <xacro:ref_taxel
            finger_num = "${finger_num}"
            finger_part = "1"
            face = "back"
            tip = ""
            origin_xyz = "-0.02 0.005 0"
            origin_rpy = "0 0 0"
            sphere_radius="0.0025"
        />
    -->
    <!-- PartA Back Taxels -->
    <!--
        <xacro:PartA_Back_Taxels reference_taxel_name = "link_${finger_num*4+1}_back_taxel" taxel_sphere_radius = "0.0025"/>
    -->
        <!-- [LINK 2, 6, 10]-->
        <link name="link_${finger_num*4+2}">
            <visual>
                <geometry>
                    <mesh filename="package://allegro_hand_description/meshes/link_2.0.STL"/>
                </geometry>
                <material name="black"/>
            </visual>

            <collision>
                <geometry>
                    <box size="${links_x} ${links_y} ${link2_z}"/>
                </geometry>
                <origin rpy="0 0 0" xyz="0 0 ${link2_z/2}"/>
            </collision>

            <inertial>
              <mass value="0.0355" />
              <origin xyz="0 0 0" rpy="0 0 0"/>
              <inertia ixx="2.63979183333e-05" ixy="6.67968e-06" ixz="4.783625e-06"
                       iyy="1.34948516667e-05" iyz="9.372e-06"
                       izz="2.63979183333e-05" />
            </inertial>
        </link>

        <joint name="joint_${finger_num*4+2}_0" type="revolute">
            <axis xyz="0 1 0"/>
            <limit effort="15" velocity="7"
                   lower="${limit_2_low+joint_safety_margin}"
                   upper="${limit_2_up-joint_safety_margin}"/>
            <parent link="link_${finger_num*4+1}"/>
            <child link="link_${finger_num*4+2}"/>
            <origin xyz="0 0 ${link1_z}"/>
            <dynamics damping="8" friction="10"/>
        </joint>

<!-- FRONT TAXEL (UPPER) -->
<!--
        <xacro:ref_taxel
            finger_num = "${finger_num}"
            finger_part = "2"
            face = "front_upper"
            tip = ""
            origin_xyz = "0.02 -0.005 0.028"
            origin_rpy = "0 0 0"
            sphere_radius="0.005"
        />
-->
    <!-- Part A/B Front Taxels -->
    <!--
        <xacro:PartAB_Front_FingerFront_Upper_Taxels reference_taxel_name = "link_${finger_num*4+2}_front_upper_taxel" taxel_sphere_radius = "0.005"/>
    -->
    <!-- BACK TAXEL -->
    <!--
        <xacro:ref_taxel
            finger_num = "${finger_num}"
            finger_part = "2"
            face = "back"
            tip = ""
            origin_xyz = "-0.02 -0.005 0.02"
            origin_rpy = "0 0 0"
            sphere_radius="0.0025"
        />
    -->
    <!-- Part A/B Front Taxels -->
    <!--
        <xacro:PartAB_Front_FingerBack_Taxels reference_taxel_name = "link_${finger_num*4+2}_back_taxel" taxel_sphere_radius = "0.0025"/>
    -->

        <!-- [LINK 3, 7, 11] -->
        <link name="link_${finger_num*4+3}">
            <visual>
                <geometry>
                    <mesh filename="package://allegro_hand_description/meshes/link_3.0.STL"/>
                </geometry>
                <material name="black"/>
            </visual>

            <collision>
                <geometry>
                    <box size="${links_x} ${links_y} ${link3_z-fingerTip_r}"/>
                </geometry>
                <origin rpy="0 0 0" xyz="0 0 ${(link3_z-fingerTip_r)/2}"/>
            </collision>

            <inertial>
              <mass value="0.0096" />
              <origin xyz="0 0 0" rpy="0 0 0"/>
              <inertia ixx="4.701248e-06" ixy="1.255968e-06" ixz="1.2936e-06"
                       iyy="3.649312e-06" iyz="1.7622e-06"
                       izz="4.701248e-06" />
            </inertial>
        </link>

        <joint name="joint_${finger_num*4+3}_0" type="revolute">
            <axis xyz="0 1 0"/>
            <limit effort="15" velocity="7"
                   lower="${limit_3_low+joint_safety_margin}"
                   upper="${limit_3_up-joint_safety_margin}"/>
            <parent link="link_${finger_num*4+2}"/>
            <child link="link_${finger_num*4+3}"/>
            <origin xyz="0 0 ${link2_z}"/>
            <dynamics damping="10" friction="12"/>
        </joint>

        <!-- [FINGER TIP] -->
        <link name="link_${finger_num*4+3}_tip">
            <visual>
                <geometry>
                    <mesh filename="package://allegro_hand_description/meshes/link_3.0_tip.STL"/>
                </geometry>
                <material name="white">
                    <color rgba=".9 .9 .9 1"/>
                </material>
            </visual>

            <collision>
                <geometry>
                    <sphere radius="${fingerTip_r}"/>
                </geometry>
            </collision>

            <inertial>
              <mass value="0.0168" />
              <origin xyz="0 0 0" rpy="0 0 0"/>
              <inertia ixx="9.68e-07" ixy="0" ixz="0"
                       iyy="9.68e-07" iyz="0"
                       izz="9.68e-07" />
            </inertial>
        </link>

        <joint name="joint_${finger_num*4+3}_tip" type="fixed">
            <parent link="link_${finger_num*4+3}"/>
            <child link="link_${finger_num*4+3}_tip"/>
            <origin rpy="0 0 0" xyz="0 0 ${link3_z-fingerTip_r}"/>
        </joint>
    <!-- FINGERTIP INCLINED PORTION REFERENCE TAXEL -->
    <!--
        <xacro:ref_taxel
            finger_num = "${finger_num}"
            finger_part = "3"
            face = "wedge"
            tip = "_tip"
            origin_xyz = "0.025 0.005 0"
            origin_rpy = "0 0 0"
            sphere_radius="0.0025"
        />
    -->
    <!-- FINGERTIP INCLINED TAXELS -->
    <!--
        <xacro:Fingertip_Inclined_Taxels reference_taxel_name = "link_${finger_num*4+3}_wedge_tip_taxel" taxel_sphere_radius = "0.0025"/>
    -->
    <!-- FINGERTIP FLAT TOP PORTION REFERENCE TAXEL (P.S. No macro is used here in order to index the taxels on the fingetip in a continuous manner)-->
    <!--
        <link name="link_${finger_num*4+3}_wedge_tip_taxel_10">
        <visual>
            <geometry>
                <sphere radius="0.0025"/>
            </geometry> 
            <material name="Orange">
                <color rgba="${255/255} ${108/255} ${10/255} 1.0"/>
            </material>
        </visual>

        <collision>
            <geometry>
                <sphere radius="0.0025"/>
            </geometry>
        </collision>
        </link>

        <joint name="joint_${finger_num*4+3}_wedge_tip_taxel_10" type="fixed">
            <parent link="link_${finger_num*4+3}_tip"/>
            <child link="link_${finger_num*4+3}_wedge_tip_taxel_10"/>
            <origin xyz="0.007 0.005 0.05" rpy="0 0 0"/>
        </joint>
    -->
    <!-- FINGERTIP FLAT TOP TAXELS (P.S. No macro is used here in order to index the taxels on the fingertip in a continuous manner)-->
    <!-- Taxel 1-->
    <!--
        <xacro:taxel 
        count = "11"
        ref_taxel_name = "link_${finger_num*4+3}_wedge_tip_taxel" 
        sphere_radius =  "0.0025"
        origin_xyz = "-0.01 0 0"
        origin_rpy = "0 0 0"
        />
        -->
    <!-- New Row-->
    <!-- Taxel 2-->
    <!--
        <xacro:taxel 
        count = "12"
        ref_taxel_name = "link_${finger_num*4+3}_wedge_tip_taxel" 
        sphere_radius =  "0.0025"
        origin_xyz = "0 -0.01 0"
        origin_rpy = "0 0 0"
        />
    -->
    <!-- Taxel 3-->
    <!--
        <xacro:taxel 
        count = "13"
        ref_taxel_name = "link_${finger_num*4+3}_wedge_tip_taxel" 
        sphere_radius =  "0.0025"
        origin_xyz = "0.01 0 0"
        origin_rpy = "0 0 0"
        />
    -->
    <!-- FINGERTIP STRAIGHT PORTION REFERENCE TAXEL (P.S. No macro is used here in order to index the taxels on the fingetip in a continuous manner)-->
        <!--
        <link name="link_${finger_num*4+3}_wedge_tip_taxel_14">
        <visual>
            <geometry>
                <sphere radius="0.0025"/>
            </geometry> 
            <material name="Orange">
                <color rgba="${255/255} ${108/255} ${10/255} 1.0"/>
            </material>
        </visual>

        <collision>
            <geometry>
                <sphere radius="0.0025"/>
            </geometry>
        </collision>
        </link>

        <joint name="joint_${finger_num*4+3}_wedge_tip_taxel_14" type="fixed">
            <parent link="link_${finger_num*4+3}_tip"/>
            <child link="link_${finger_num*4+3}_wedge_tip_taxel_14"/>
            <origin xyz="-0.02 0.005 0.02" rpy="0 0 0"/>
        </joint>
 -->
    <!--FINGERTIP STRAIGHT PORTION TAXELS (P.S. No macro is used here in order to index the taxels on the fingertip in a continuous manner)-->

    <!-- Taxel 1-->
    <!--
        <xacro:taxel 
        count = "15"
        ref_taxel_name = "link_${finger_num*4+3}_wedge_tip_taxel" 
        sphere_radius =  "0.0025"
        origin_xyz = "0 0 -0.009"
        origin_rpy = "0 0 0"
        />
    -->
    <!-- Taxel 2-->
    <!--
        <xacro:taxel 
        count = "16"
        ref_taxel_name = "link_${finger_num*4+3}_wedge_tip_taxel" 
        sphere_radius =  "0.0025"
        origin_xyz = "0 0 -0.009"
        origin_rpy = "0 0 0"
        />
        -->
    <!-- New Row-->
    <!-- Taxel 3-->
    <!--
        <xacro:taxel 
        count = "17"
        ref_taxel_name = "link_${finger_num*4+3}_wedge_tip_taxel" 
        sphere_radius =  "0.0025"
        origin_xyz = "0 -0.009 0"
        origin_rpy = "0 0 0"
        />
        -->
    <!-- Taxel 4-->
    <!--
        <xacro:taxel 
        count = "18"
        ref_taxel_name = "link_${finger_num*4+3}_wedge_tip_taxel" 
        sphere_radius =  "0.0025"
        origin_xyz = "0 0 0.009"
        origin_rpy = "0 0 0"
        />
        -->
    <!-- Taxel 5-->
    <!--
        <xacro:taxel 
        count = "19"
        ref_taxel_name = "link_${finger_num*4+3}_wedge_tip_taxel" 
        sphere_radius =  "0.0025"
        origin_xyz = "0 0 0.009"
        origin_rpy = "0 0 0"
        />
      -->  
    </xacro:macro>
    <!-- [[END]] THREE FINGER MACRO -->

    <!-- FINGERS -->
    <!-- RIGHT HAND due to which finger is number 0 -->
    <!-- for LEFT HAND switch the sign of the **offset_origin_y** and **finger_angle_r** parameters-->
    <xacro:finger
            finger_num="0"
            offset_origin_x="${offset_origin_x_const}"
            offset_origin_y="${offset_origin_y_const}"
            offset_origin_z="${offset_origin_z_const}"
            finger_angle_r="-${5.0*DEG2RAD}"
            />
    <xacro:finger
            finger_num="1"
            offset_origin_x="${offset_origin_x_const}"
            offset_origin_y="0"
            offset_origin_z="${offset_origin_z_mid_const}"
            finger_angle_r="0.0"
            />
    <xacro:finger
            finger_num="2"
            offset_origin_x="${offset_origin_x_const}"
            offset_origin_y="-${offset_origin_y_const}"
            offset_origin_z="${offset_origin_z_const}"
            finger_angle_r="${5.0*DEG2RAD}"
            />

    <!-- ============================================================================= -->
</xacro:macro>
</robot>
