# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: todo_group_name
  joint_model_group_pose: todo_state_name
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - joint_0_0
    - joint_1_0
    - joint_2_0
    - joint_3_0
    - joint_12_0
    - joint_13_0
    - joint_14_0
    - joint_15_0
    - joint_4_0
    - joint_5_0
    - joint_6_0
    - joint_7_0
    - joint_8_0
    - joint_9_0
    - joint_10_0
    - joint_11_0
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []
middle_controller:
  type: position_controllers/JointPositionController
  joints:
    - joint_4_0
    - joint_5_0
    - joint_6_0
    - joint_7_0
  gains:
    joint_4_0:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_5_0:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_6_0:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_7_0:
      p: 100
      d: 1
      i: 1
      i_clamp: 1